name: Setup Process Composition

description: 'Setup flutter and languages environment'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '12.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
        cache: true

    - name: Get Dependencies
      run: flutter pub get
      shell: bash
