name: Setup Process Composition

description: 'Setup flutter and languages environment'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      name: Flutter Action
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
        cache: true
    - name: Get Dependencies
      run: flutter pub get
