name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/setup
      - name: Run UnitTest with Coverage
        run: flutter test --no-test-assets --coverage --coverage-path=~/coverage/lcov.info
      - name: Record Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ~/coverage/lcov.info
          flags: unittests

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/setup
      - name: Run Lint
        run: flutter analyze

  # コードの自動生成が漏れているか確認
  check-diff-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/setup
      - name: Run Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Check diff
        run: git diff --quiet --exit-code
